name: quevault_app
description: "QueVault - Offline Password Manager"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  random_password_generator: ^0.2.1
  clipboard: ^2.0.2
  hooks_riverpod: ^2.6.1
  shadcn_ui: ^0.29.0
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.6
  pointycastle: ^3.7.3
  introduction_screen: ^3.1.14
  local_auth: ^2.3.0
  flutter_expandable_fab: ^2.5.2
  file_picker: ^10.3.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/quevault-logo.png"
  min_sdk_android: 31
  min_sdk_ios: 11
  prefix: "Icon"
  remove_alpha_ios: true
  foreground_android: "#000000"
  foreground_ios: "#000000"
  output_image_path: "assets/images/icons/icon.png"
  output_dir: "assets/imagesicons"

flutter:
  uses-material-design: true
